"""Capabilities consumed by controllers; no runtime Supervisor dependency."""
from typing import Any, Mapping, Protocol


class ValveCommands(Protocol):
    async def set_valve(self, valve_id: str, state: bool, *, reason: str = '') -> None: ...
    def report_event(self, kind: str, message: str) -> None: ...


class ProcessCommands(ValveCommands, Protocol):
    snapshot: Mapping[str, Any]

    async def set_mfc_setpoint(self, mfc_id: str, sccm: float) -> float: ...
    async def start_fill_regulation(self, *, valve: str, gauge: str, target_torr: float,
                                    pulse_on_s: float, pulse_off_s: float,
                                    tolerance_frac: float = 0.2) -> None: ...
    async def stop_fill_regulation(self) -> None: ...


class RecipeHost(ProcessCommands, Protocol):
    async def finish_run(self) -> None: ...


class PrestartHost(ProcessCommands, Protocol):
    @property
    def run_in_progress(self) -> bool: ...

    async def hv_off(self, *, reason: str = '') -> None: ...
    async def supplies_output_on(self, *, sample_bias_v: float = 0.0,
                                 polarity: int = 1, reason: str = '') -> None: ...
    async def supplies_output_off(self, *, reason: str = '') -> None: ...
